services:
  db:
    image: mysql:5.7
    container_name: wordpress-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    platform: 
      linux/amd64
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      TAR_OPTIONS: --no-same-owner 
    volumes:
      - wp:/var/www/html
      - ./plugins:/plugins
      - ./custom-functions:/custom-functions

    ports:
      - "8080:80"
    platform: 
      linux/amd64

volumes:
  mysql_data:
  wp:
